---
# tasks file for jdk
- name: 创建java安装目录
  file:
    path: "{{ install_dir }}"
    state: directory
    mode: 0755

- name: 复制并解压 jdk包 到安装目录
  unarchive:
    src: "{{jdk_package_name}}"
    dest: "{{ install_dir }}"

- name: 创建软连接
  file:
    src: "{{ install_dir + jdk_version }}"
    dest: "{{ soft_dir }}"
    state: link

- name: 设置环境变量
  lineinfile:
    dest: "{{ env_file }}"
    insertafter: "{{ item.position }}"
    line: "{{ item.value }}"
    state: present
  with_items:
    - {position: EOF, value: "\n"}
    - {position: EOF, value: "{{ 'export JAVA_HOME=' + soft_dir}}"}
    - {position: EOF, value: "export PATH=$JAVA_HOME/bin:$PATH"}
    - {position: EOF, value: "export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"}
